language: node_js
node_js:
- node
deploy:
  provider: npm
  email: nugetpowerbi@microsoft.com
  api_key:
    secure: KTMw5xnlse7TrK3JGILwzoO1z9Wu9W7wyQmFN8jgMwNE8Ak2m5KrEtjrO0zjLdhVJnl9Me7KVITgHj6tr3KYWOo5Radl8uBZTjdfBCJQdTbBU4ypqJnKOFLtHwNJQowdVNfB6YqtlvJRYqRJKNY5yH+7AiComXTov5hO/T+oPWwozdpRycLdH0L40CsFnjc7mQKi1IBxurPbu/NmvwhMFjKYiE/DNQRkiIpPCEK3yrVtKOtbDSmLX8VclkRpoX9FceZvbDxnI+YQWG+SmPd5XHJrk6wqHLmHBD7JhipfYgD3YDhPAbOzl3LBwUvHXWuJ7ucmcRDaC9ht4SgRbXHgOYZCV7vTcoBL3d7siAEEYSYnm57XLbZqE7m053jsaj1EraU+j5L9h63NqjuZIwMIL8eH1ilpuG8b7BKbJUdWAeqfIeYwjDsoa3+p9mD/FfEWsjvLXSNtoDI/I1QQYzgkA2bIAu3OqBi/6pG0S0JF4ihUol2rHeznt4DCiK+yDfsZ63XNbR/zCMluDQQEjitoc+QMOaU31D0v36c/CGLux1SeulfPPrDwsg01o1U8wO3opV75tPvg9zhnBAfKHZBZZKutuy25Xvi8H8kZHzM11Bsy0q2PBwx+Hn7wwy2jkLqJ03BSmCKJHxcdrWvWUmY29L8zcnwUkJwzYhO6Xg24rFA=
  on:
    tags: true
    repo: Microsoft/powerbi-router
    branch: dev
